# Functions
Python knows you will need many tools.
***
- ## Built-in functions:

In [1]:
lovely_simple_tuple = (1,3,5,7,9)

In [2]:
sum(lovely_simple_tuple)

25

In [3]:
lovely_simple_list = list(lovely_simple_tuple)
lovely_simple_list

[1, 3, 5, 7, 9]

In [4]:
min(lovely_simple_list), max(lovely_simple_list)

(1, 9)

In [5]:
float(3)

3.0

In [6]:
len(lovely_simple_list)

5

In [35]:
round(3.54,1)

3.5

In [7]:
type( sum )

builtin_function_or_method

 ***
 - ## Pesonalized functions
 
 What if we want to define our own functions?

In [8]:
def new_function(input_value):
    output_value = input_value
    return output_value

*Example:*

    1. Define a function which check if the list is not empty

In [9]:
def is_empty_one(input_list):
    return input_list == []

def is_empty_two(input_list):
    answer = len(input_list) == 0
    return answer

In [10]:
is_empty_one(lovely_simple_list)

False

In [11]:
is_empty_two(lovely_simple_list)

False

*Note* 

    local varaibles and global varaibales

In [12]:
answer

NameError: name 'answer' is not defined

    2. Define a function which compute the points of a team

In [13]:
global win_point, tie_point
win_point = 2
tie_point = 1

def compute_points(team_wins,team_ties):
    points = team_ties * tie_point + team_wins * win_point
    return points

dortmund_points = compute_points(4,1)
dortmund_points

9

**Exercise**

1. Define a function which checks if the two list have the same length.

    returns **True** if they have otherwise return **False**

In [14]:
def justice_function(list_one,list_two):
    # Do something
    return

2. Define a function which gets two list of same length and then returns the maximum of both lists.
    
    example:

    list_one = [1,10,100]
    
    list_two = [-10,102,99]
    
    should returns 102

In [15]:
def largest_of_two():
    return

*Note:* **Ask Python your Question?**

In [16]:
sum?

In [17]:
def is_empty_one(input_list):
    """
    This function gets a list and check if it is empty.
    return True if it is empty and False if it is not.
    """
    return input_list == []

In [18]:
is_empty_one?

***
***
# The import technique

What if we want to use previously defined functions.


In [19]:
import lists_manipulation_module

In [20]:
extract_numbers?

Object `extract_numbers` not found.


In [21]:
lists_manipulation_module.extract_numbers([1,2,'abc','2',4.0])

[1, 2, 4.0]

**The point (.) is very familiar for us! isn't it?**

In [22]:
type(lists_manipulation_module)

module

In [23]:
type(lists_manipulation_module.extract_numbers)

function

Call a module with its Nickname

In [24]:
import lists_manipulation_module as lsts_mnpltn

In [25]:
lsts_mnpltn.extract_numbers([1,2,'abc','2',4.0])

[1, 2, 4.0]

***
# written modules

## numpy

In [26]:
import numpy as np

In [27]:
np.array(lovely_simple_list)

array([1, 3, 5, 7, 9])

In [34]:
lovely_simple_nparray = np.array(lovely_simple_list)
lovely_simple_nparray

array([1, 3, 5, 7, 9])

In [28]:
np.zeros( (3,3) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
random_array = np.random.rand(3,5)
random_array

array([[0.12452203, 0.34174467, 0.59280754, 0.10084373, 0.45229595],
       [0.77423589, 0.49521826, 0.88070086, 0.4424564 , 0.13345321],
       [0.6930536 , 0.44346915, 0.12078853, 0.00552494, 0.03750168]])

**Check yourself:**
    - np.sqrt, np.abs, np.log, ...
    - np.where, np.random.choice, np.reshape, ...