# Functions
Python knows you will need many tools.
***
- ## Built-in functions:

In [4]:
lovely_simple_tuple = (1,3,5,7,9)

In [3]:
sum(lovely_simple_tuple)

25

In [5]:
lovely_simple_list = list(lovely_simple_tuple)
lovely_simple_list

[1, 3, 5, 7, 9]

In [6]:
min(lovely_simple_list), max(lovely_simple_list)

(1, 9)

In [7]:
float(3)

3.0

In [8]:
len(lovely_simple_list)

5

In [10]:
round(3.5432,2)

3.54

In [13]:
type( len )

builtin_function_or_method

In [33]:
user_given_num = int( input('Please enter a number') )

Please enter a number5


In [35]:
type(user_given_num)

int

 ***
 - ## Pesonalized functions
 
 What if we want to define our own functions?

In [15]:
def new_function(input_value):
    output_value = input_value
    return output_value

new_function(3)

3

*Example:*

    1. Define a function which check if the list is not empty

In [17]:
def is_empty_one(input_list):
    return input_list == []

def is_empty_two(input_list):
    answer = len(input_list) == 0
    return answer

In [20]:
is_empty_one(lovely_simple_list)

False

In [21]:
is_empty_two(lovely_simple_list)

False

*Note* 

    local varaibles and global varaibales

In [22]:
answer

NameError: name 'answer' is not defined

    2. Define a function which compute the points of a team

In [24]:
global win_point, tie_point
win_point = 3
tie_point = 2

def compute_points(team_wins,team_ties):
    points = team_ties * tie_point + team_wins * win_point
    return points

dortmund_points = compute_points(4,1)
dortmund_points

14

**Exercise**

1. Define a function which checks if the two list have the same length.

    returns **True** if they have otherwise return **False**

In [30]:
def justice_function(list_one,list_two):
    # Do something
    status = len(list_one) == len(list_two)
    return status

justice_function(lovely_simple_list,lovely_simple_list)

True

2. Define a function which gets two list of same length and then returns the maximum of both lists.
    
    example:

    list_one = [1,10,100]
    
    list_two = [-10,102,99]
    
    should returns 102

In [29]:
def largest_of_two(list_one,list_two):
    return max( [max(list_one),max(list_two)] )

largest_of_two(lovely_simple_list,lovely_simple_list+[2])

9

*Note:* **Ask Python your Question?**

In [36]:
sum?

In [41]:
sum(lovely_simple_list)

28

In [43]:
def is_empty_one(input_list):
    """
    This function gets a list and check if it is empty.
    return True if it is empty and False if it is not.
    """
    
    return input_list == []

In [44]:
is_empty_one?

# Python City
 - The city is made up of objects and building blocks.
 - We use functions as tools

<img src="Figures/python-city.png" alt="Drawing" style="width: 600px;" align = "center"/>

***
***
# Modules and the import technique

Lets use the previously made tools.

<img src="Figures/modules of tools.png" alt="Drawing" style="width: 600px;" align = "left"/>

In [3]:
import lists_manipulation_module

In [47]:
lists_manipulation_module.extract_numbers?

In [49]:
lists_manipulation_module.extract_numbers([2,'3',4.5,5,'absc'])

[2, 4.5, 5]

**The point (.) is very familiar for us! isn't it?**

In [23]:
type(lists_manipulation_module)

module

In [24]:
type(lists_manipulation_module.extract_numbers)

function

Call a module with its Nickname

In [7]:
import lists_manipulation_module as lsts_mnpltn

In [8]:
lsts_mnpltn.extract_numbers([1,2,'abc','2',4.0])

[1, 2, 4.0]

In [27]:
from lists_manipulation_module import extract_numbers

In [28]:
extract_numbers([1,2,'abc','2',4.0])

[1, 2, 4.0]

***
# written modules

## numpy

In [10]:
import numpy as np

In [11]:
np.array(lovely_simple_list)

array([1, 3, 5, 7, 9, 2])

In [12]:
lovely_simple_nparray = np.array(lovely_simple_list)
lovely_simple_nparray

array([1, 3, 5, 7, 9, 2])

In [15]:
np.zeros( (3,3) )

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [33]:
random_array = np.random.rand(3,5)
random_array

array([[0.94262381, 0.89615744, 0.5966562 , 0.01494326, 0.82232926],
       [0.11330671, 0.205475  , 0.3178023 , 0.32951464, 0.44048695],
       [0.13794716, 0.44310483, 0.32423081, 0.30967057, 0.82376095]])

In [18]:
np.random.uniform()

0.8497539862094322

**Check yourself:**
    - np.sqrt, np.abs, np.log, ...
    - np.where, np.random.choice, np.random.uniform, np.reshape, ...

In [19]:
np.where?