# Numpy

In [1]:
import numpy as np

In [14]:
lovely_simple_array = np.arange(0,10)
lovely_simple_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.sum(lovely_simple_array), np.average(lovely_simple_array), np.median(lovely_simple_array)

(45, 4.5, 4.5)

In [17]:
np.reshape(lovely_simple_array, (2,5) )

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
lovely_simple_array * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [45]:
lovely_simple_array != 0

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

Product of two arrays with **the same** shape

In [19]:
lovely_simple_array * np.arange(10,20)

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171])

Product of two arrays with **not exactly the same** shape

In [37]:
array_one = np.reshape( np.arange(0,10), (2,5) )
array_two = np.arange(0,5)

print('First array is \n',array_one)
print('Second array is \n',array_two)

print('The production of the two is \n', array_one * array_two)
print('\n That is how Python broadcasted array_two to array_one')

First array is 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
Second array is 
 [0 1 2 3 4]
The production of the two is 
 [[ 0  1  4  9 16]
 [ 0  6 14 24 36]]

 That is how Python broadcasted array_two to array_one


In [39]:
phi = np.arange(0,5)
psi = np.arange(5,10)

np.dot(phi,psi)

80

In [40]:
np.exp(phi)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [42]:
np.sum( np.log(phi) )

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


-inf

### Masking

In [43]:
mask = [False, True, True, False, True]
phi[mask]

array([1, 2, 4])

In [44]:
positive_mask = phi > 0
positive_mask

array([False,  True,  True,  True,  True])

In [46]:
phi[positive_mask]

array([1, 2, 3, 4])

In [49]:
print( np.log(phi[positive_mask]),'\n the sum is: ' ,np.sum( np.log(phi[positive_mask]) ) )

[0.         0.69314718 1.09861229 1.38629436] 
 the sum is:  3.1780538303479453


### Save and load nparrays

In [50]:
np.save('log_positive_phi.npy',np.log(phi[positive_mask]))

In [52]:
results = np.load('women_football.npy')

- **Example**

    The data of two teams are recorded in 'women_football.npy' array.
    
    Check the illustartion bellow to find the data manual:

# Matplotlib